version: '3.8'

services:
  gin-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-service-dev
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
      - LOG_LEVEL=debug
      - LOG_FORMAT=text
      - LOG_OUTPUT=stdout
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gin-network-dev
    # For development, you might want to run with hot reload
    # command: ["go", "run", "cmd/server/main.go"]

networks:
  gin-network-dev:
    driver: bridge
