version: '3.8'

services:
  gin-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-service
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - LOG_OUTPUT=stdout
    volumes:
      - ./logs:/app/logs
      - ./configs:/app/configs:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - gin-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: gin-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - gin-service
    restart: unless-stopped
    networks:
      - gin-network
    profiles:
      - production

networks:
  gin-network:
    driver: bridge
